version: "3"

services:
  app:
    image: node:16-alpine3.11
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /node_modules
    command: sh -c "yarn install && yarn start"